# Generated by Django 5.2.11 on 2026-02-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_invoice_parsed_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('TRANSPORT', '交通费'), ('ACCOMMODATION', '住宿费'), ('OTHER', '其他费用')], default='OTHER', max_length=20),
        ),
    ]
