# Generated by Django 5.2.11 on 2026-02-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_department_user_real_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='0', max_length=50, unique=True, verbose_name='发票号码'),
        ),
    ]
