# Generated by Django 5.2.11 on 2026-04-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_email_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='service_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='服务结束时间'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='service_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='服务开始时间'),
        ),
    ]
